name: deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  run_update:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: print out run update
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 203.194.113.54
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        command_timeout: 30m
        script: | 
          cd /home/apps/ilyas/web-spring 
          git pull origin main
          mvn clean install
          ./stop.sh
          cp -f /home/apps/ilyas/web-spring/target/web-spring-0.0.1-SNAPSHOT.jar /home/apps/ilyas/web-spring.jar
          ./start_silent.sh
          echo "Selesai"
